Models/Book.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.AuthorBook = new HashSet<AuthorBook>();
        }
    
        public int bookId { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> dateEdition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthorBook> AuthorBook { get; set; }
    }
}

Models/SearchBook.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace libreria.Models
{
    public class SearchBook
    {
        public string title { get; set; }
        public Nullable<System.DateTime> dateEdition { get; set; }
        public string author { get; set; }        
    }
}

Controllers/BookController.cs
using libreria.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace libreria.Controllers
{
    public class BookController : Controller
    {
        // GET: Book
        public ActionResult Index(string title, string dateEdition, string author)
        {

            try
            {
                using (var db = new LibraryEntities1())
                {
                    string conditional = "";

                    if (dateEdition != "" && dateEdition != null) {
                        conditional = " AND bk.dateEdition = '" + dateEdition + "'";
                    }

                    if (title != "" && title != null)
                    {
                        title = " AND bk.title LIKE '%" + title + "%'";
                    }

                    string sql = @"select 
                                DISTINCT bk.bookId,  bk.title, bk.dateEdition, dbo.getTotalAuthor(bk.bookId) as 'total'
                                from 
                                [dbo].[AuthorBook] as ab ,  [dbo].[Book] as bk
                                where 
                                ab.bookId = bk.bookId  " + conditional + " " + title;

                    List<BookCE> list = db.Database.SqlQuery<BookCE>(sql).ToList();
                    return View(list);
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error to create a Loan -  " + ex.Message);
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            try
            {
                using (var db = new LibraryEntities1())
                {
                    Book book = db.Book.Where(b => b.bookId == id).FirstOrDefault();                    
                    List<Author> listAuthors = db.Author.ToList();

                    List<int> authorsSelected = db.AuthorBook.Where(ab => ab.bookId == book.bookId)
                                          .Select(b => b.authorId)
                                          .ToList();

                    BookAuthorCE bookAuthorCE = new BookAuthorCE();
                    bookAuthorCE.bookId = book.bookId;
                    bookAuthorCE.title = book.title;
                    bookAuthorCE.dateEdition = book.dateEdition;
                    bookAuthorCE.authorsSelected = authorsSelected;
                    bookAuthorCE.authors = listAuthors;

                    return View(bookAuthorCE);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error to edit a book -  " + ex.Message);
                return View();
            }
        }


        [HttpPost]
        public ActionResult Edit(BookAuthorCE bookAuthorCE)
        {


            try
            {
                using (var db = new LibraryEntities1())
                {
                    // prepare book
                    Book book = db.Book.Find(bookAuthorCE.bookId);
                    book.title = bookAuthorCE.title;
                    book.dateEdition = bookAuthorCE.dateEdition;
                    //db.SaveChanges();


                    // remove authors of the book
                    var removeAuthors = (from authorBook in db.AuthorBook
                                  where authorBook.bookId== bookAuthorCE.bookId                                     
                                  select authorBook).ToList();

                    if (removeAuthors != null)
                    {
                        db.AuthorBook.RemoveRange(removeAuthors);                        
                    }
                    //db.SaveChanges();



                    foreach (var authorId in bookAuthorCE.authorsSelected)
                    {
                        AuthorBook authorBook = new AuthorBook();
                        authorBook.bookId = book.bookId;
                        authorBook.authorId = authorId;

                        db.AuthorBook.Add(authorBook);
                    }

                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error to create a book -  " + ex.Message);
                return View();
            }
        }


        public ActionResult AuthorBookList()
        {

            using (var db = new LibraryEntities1())
            {
                return PartialView(db.Author.ToList());
            }

        }



        public ActionResult Create()
        {
            using (var db = new LibraryEntities1()) {

                List<Author> listAuthors = db.Author.ToList();

                BookAuthorCE bookAuthorCE = new BookAuthorCE();
                bookAuthorCE.authors = listAuthors;
                return View(bookAuthorCE);
            }
        }

        [HttpPost]
        public ActionResult Create(BookAuthorCE bookAuthorCE)
        {
            try
            {
                using (var db = new LibraryEntities1())
                {
                    // prepare book
                    Book book = new Book();
                    book.title = bookAuthorCE.title;
                    book.dateEdition = bookAuthorCE.dateEdition;

                    db.Book.Add(book);                    

                    foreach (var authorId in bookAuthorCE.authorsSelected)
                    {
                        AuthorBook authorBook = new AuthorBook();
                        authorBook.bookId = book.bookId;
                        authorBook.authorId = authorId;

                        db.AuthorBook.Add(authorBook);
                    }

                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error to create a book -  " + ex.Message);
                return View();
            }
        }

        public ActionResult searchBook()
        {
            using (var db = new LibraryEntities1())
            {
                SearchBook searchBook = new SearchBook();                
                return View(searchBook);
            }
        }

        [HttpPost]
        public ActionResult searchBook(SearchBook searchBook)
        {
            try
            {
                using (var db = new LibraryEntities1())
                {
                    // prepare book
                    /*Book book = new Book();
                    book.title = bookAuthorCE.title;
                    book.dateEdition = bookAuthorCE.dateEdition;

                    db.Book.Add(book);

                    foreach (var authorId in bookAuthorCE.authorsSelected)
                    {
                        AuthorBook authorBook = new AuthorBook();
                        authorBook.bookId = book.bookId;
                        authorBook.authorId = authorId;

                        db.AuthorBook.Add(authorBook);
                    }

                    db.SaveChanges();*/
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error to create a book -  " + ex.Message);
                return View();
            }
        }


    }
}

Views/Book/AuthorBookList.cshtml
@model IEnumerable<libreria.Models.Author>

<select class="form-control selectpicker" name="authorId" id="authorId" multiple>
    @foreach (var item in Model)
    {
        <option value="@item.authorId">@item.name  </option>
    }
</select>

Views/Book/Create.cshtml
@model libreria.Models.BookAuthorCE


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateEdition, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateEdition, new { htmlAttributes = new { @class = "form-control", @type="date" } })
                @Html.ValidationMessageFor(model => model.dateEdition, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">

            <div class="control-label col-md-2">
                LIsta de autores
            </div>

            <div class="col-md-10">
                @Html.DropDownListFor(m => m.authorsSelected,
                Model.authors.Select(x => new SelectListItem { Text = x.name, Value = x.authorId.ToString() }), new { @class = "form-control chosen-select", @multiple="true" })
                @Html.ValidationMessageFor(model => model.authorsSelected, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        //$(".chosen-select").chosen();
    </script>
}

Views/Book/Edit.cshtml
@model libreria.Models.BookAuthorCE

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.bookId)

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateEdition, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateEdition, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.dateEdition, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">

            <div class="control-label col-md-2">
                LIsta de autores
            </div>

            <div class="col-md-10">

                @Html.ListBoxFor(x => x.authorsSelected,
                new MultiSelectList(Model.authors, "authorId", "name"), new { @class = "form-control chosen-select", @multiple = "true" })
                @Html.ValidationMessageFor(model => model.authorsSelected, "", new { @class = "text-danger" })


            </div>
        </div>


       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script>
            //$(".chosen-select").chosen();

        $(function () {
            //$('#authorsSelected').val('@Model.authorsSelected');
        });

    </script>


    

}

Views/Book/Index.cshtml
@model IEnumerable<libreria.Models.BookCE>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div>
    @Html.Action("searchBook", "Book")
</div>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Titile
        </th>
        <th>
            Edition
        </th>
        <th>
            Authors
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dateEdition)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.total)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.bookId }) 
            </td>
        </tr>
    }

</table>

Views/Book/searchBook.cshtml
@model libreria.Models.SearchBook


@using (Html.BeginForm("Index", "Book", FormMethod.Get)) 
{   
    
    <div class="form-horizontal">
        <h4>SearchBook</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateEdition, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateEdition, new { htmlAttributes = new { @class = "form-control", @type="date" } })
                @Html.ValidationMessageFor(model => model.dateEdition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
        </div>
    </div>
}